replicaCount: 1

image:
  repository: go-hello-world
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
